export type BranchClassRecord = {
  id: string;
  idClass?: number | string;
  rubroId: string;
  date: string;
  time: string;
  capacity: number;
  available?: number;
  price?: number;
  refund?: number;
  instructor?: string;
  instructorId?: string;
  branchId?: number;
  idBranchDiscipline?: number;
  idUser?: number;
  duration?: number;
  creditUsage?: number;
  creditRefund?: number;
  status?: string | number;
  disciplineName?: string;
  bookingSource?: "api" | "planned" | "published";
  syncStatus?: "synced" | "pending-backend";
} & Record<string, unknown>;
